# Generated by Django 3.2.6 on 2022-07-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='now', upload_to='images/')),
                ('item_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=40)),
                ('price', models.CharField(default='now', max_length=10)),
            ],
        ),
    ]
