# Generated by Django 3.2.6 on 2022-07-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='now', upload_to='logo/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='1000', max_length=10),
        ),
    ]
